### ISSUE TITLE
Add gRPC web support

### ISSUE THREAD

**Issue by Avarei** [crossplane-contrib/provider-argocd#102]
### What problem are you facing?

Some ArgoCD instances of my customers are behind a proxy without http2 support.
The argocd cli allows the use of gRPC-Web in such cases using the `--grpc-web` and `--grpc-web-root-path` flags.

### How could Crossplane help solve your problem?

Add grpcWeb and grpcWebRootPath to the ProviderConfig and pass it to the client library.

**Comment by janwillies** [comment]
This has been added in #103
