### ISSUE TITLE
Add support for labels on Cluster

### ISSUE THREAD

**Issue by clementblaise** [crossplane-contrib/provider-argocd#23]
### What problem are you facing?
Filtering with [Generators-Cluster](https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/) only supports labels, there is currently no way to add labels on a Cluster.

### How could Crossplane help solve your problem?
Provide an option to pass labels on the Cluster resource

**Comment by MisterMX** [comment]
Thanks for opening this issue, @clementblaise.

I think this can be done by adding a new property `spec.forProvider.labels` and adding them to the create request.

Feel free to open a PR to add this feature!

**Comment by clementblaise** [comment]
Indeed @MisterMX, started making the changes I wanted to open a PR. The problem I have is updating Argocd to least v2.2.0 when they added [labels](https://github.com/argoproj/argo-cd/blob/6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a/pkg/apis/application/v1alpha1/types.go#L1286 ) to the Cluster type, I am having issue with indirect dependencies such as :

```
go: github.com/argoproj/argo-cd/v2@v2.3.0 requires
        gomodules.xyz/notify@v0.1.0 requires
        github.com/appscode/go@v0.0.0-20190808133642-1d4ef1f1c1e0 requires
        github.com/flosch/pongo2@v0.0.0-20181225140029-79872a7b2769 requires
        github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1  
```

**Comment by MisterMX** [comment]
I haven't seen this issue so far, but it seems to be related to https://github.com/golang/go/issues/33546.

**Comment by clementblaise** [comment]
I opened #24, took the opportunity to add annotations and project option as well
