### ISSUE TITLE
Repository controller doesn't update ressource on password change

### ISSUE THREAD

**Issue by wotolom** [crossplane-contrib/provider-argocd#36]
### What happened?

The [isUpToDate method](https://github.com/crossplane-contrib/provider-argocd/blob/18c39395956db553ddf7f5b303ed860c99e0edd0/pkg/controller/repositories/controller.go#L382) does not check if the password provided via secret changed.
The workaround is currently to trigger an update-call by changing another field in the repo claim.

### How can we reproduce it?

Deploy secret with e.g. token, deploy repo referencing the secret (see example). 
Write a new token in the secret or reference another secret with a new token. 
-> no update call/request + new token is not being used

**Comment by oskisk** [comment]
/fresh

I would like to contribute to this issue.
