### ISSUE TITLE
Getting no matches for kind "ProviderConfig" in version "argocd.crossplane.io/v1alpha1"

### ISSUE THREAD

**Issue by kshitijcode** [crossplane-contrib/provider-argocd#47]
### What happened?

We were trying to setup ArgoCD cross plane provider with cross-plane following the steps mentioned in the ReadME.

When trying to run 

`cat << EOF | kubectl apply -f -
apiVersion: argocd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: argocd-provider
spec:
  serverAddr: argocd-server.argocd.svc:443
  insecure: true
  plainText: false
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: argocd-credentials
      key: authToken
EOF`

it gives the following error

error: unable to recognize "STDIN": no matches for kind "ProviderConfig" in version "argocd.crossplane.io/v1alpha1"

All the cross-plane pods are healthy.

**Comment by MisterMX** [comment]
It seems the CRDs in `package/crds` haven't been installed. If you install the provider through Crossplane as a [package](https://docs.crossplane.io/v1.11/concepts/), it will do the installation for you. Otherwise (i.e. for local debugging) you have to do it manually.

**Comment by kshitijcode** [comment]
I installed it using 
`kubectl create namespace crossplane-system
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update

helm install crossplane --namespace crossplane-system crossplane-stable/crossplane
`
